{
//=========Macro generated from canvas: MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0/c
//=========  (Fri Aug 19 16:45:15 2016) by ROOT version5.34/18
   TCanvas *MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0 = new TCanvas("MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetHighLightColor(2);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->Range(-5.974187,-1.216458,10.1434,8.844365);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetFillColor(0);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetBorderMode(0);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetBorderSize(2);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetTickx(1);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetTicky(1);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetLeftMargin(0.2155525);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetRightMargin(0.07094134);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetTopMargin(0.08392603);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetBottomMargin(0.1209104);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetFrameBorderMode(0);
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetFrameBorderMode(0);
   
   TH2F *dummy = new TH2F("dummy","",1,-2.5,9,8,0,8);
   dummy->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#33cc33");
   dummy->SetFillColor(ci);
   dummy->GetXaxis()->SetTitle("#mu");
   dummy->GetXaxis()->SetLabelFont(42);
   dummy->GetXaxis()->SetLabelOffset(0.007);
   dummy->GetXaxis()->SetTitleSize(0.05);
   dummy->GetXaxis()->SetTitleOffset(0.95);
   dummy->GetXaxis()->SetTitleFont(42);
   dummy->GetYaxis()->SetBinLabel(1,"TTH Tags");
   dummy->GetYaxis()->SetBinLabel(2,"VBF Tag 1");
   dummy->GetYaxis()->SetBinLabel(3,"VBF Tag 0");
   dummy->GetYaxis()->SetBinLabel(4,"Untagged 3");
   dummy->GetYaxis()->SetBinLabel(5,"Untagged 2");
   dummy->GetYaxis()->SetBinLabel(6,"Untagged 1");
   dummy->GetYaxis()->SetBinLabel(7,"Untagged 0");
   dummy->GetYaxis()->SetBinLabel(8,"");
   dummy->GetYaxis()->SetLabelFont(42);
   dummy->GetYaxis()->SetLabelOffset(0.007);
   dummy->GetYaxis()->SetTitleSize(0.05);
   dummy->GetYaxis()->SetTitleOffset(1.15);
   dummy->GetYaxis()->SetTitleFont(42);
   dummy->GetZaxis()->SetLabelFont(42);
   dummy->GetZaxis()->SetLabelOffset(0.007);
   dummy->GetZaxis()->SetTitleSize(0.05);
   dummy->GetZaxis()->SetTitleFont(42);
   dummy->Draw("");
   TBox *box = new TBox(0.2848791,0,1.194908,7.995);

   ci = TColor::GetColor("#33cc33");
   box->SetFillColor(ci);
   box->SetLineStyle(0);
   box->Draw();
   TLine *line = new TLine(0.713603,0,0.713603,8);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1,0,1,8);

   ci = TColor::GetColor("#ff0000");
   line->SetLineColor(ci);
   line->SetLineStyle(7);
   line->SetLineWidth(5);
   line->Draw();
   TLatex *   tex = new TLatex(0.57,0.59,"#hat{#mu} =   0.71 ^{#font[122]{+}0.48}_{#font[122]{-}0.43}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.57,0.5,"m_{H} = 125.09 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(8);
   grae->SetName("");
   grae->SetTitle("");
   grae->SetFillColor(1);
   grae->SetLineWidth(2);
   grae->SetMarkerStyle(21);
   grae->SetMarkerSize(1.5);
   grae->SetPoint(0,3.952993,0.5);
   grae->SetPointError(0,3.694812,4.638847,0,0);
   grae->SetPoint(1,-0.5778571,1.5);
   grae->SetPointError(1,1.557002,1.871402,0,0);
   grae->SetPoint(2,1.97557,2.5);
   grae->SetPointError(2,1.146809,1.545381,0,0);
   grae->SetPoint(3,0.1470715,3.5);
   grae->SetPointError(3,1.354289,1.484261,0,0);
   grae->SetPoint(4,0.2813125,4.5);
   grae->SetPointError(4,0.6992684,0.8983757,0,0);
   grae->SetPoint(5,0.800548,5.5);
   grae->SetPointError(5,0.4562548,0.6012116,0,0);
   grae->SetPoint(6,0.6917508,6.5);
   grae->SetPointError(6,1.170305,1.558426,0,0);
   grae->SetPoint(7,-999,7.5);
   grae->SetPointError(7,0,0,0,0);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","",100,-1099.759,109.351);
   Graph_Graph1->SetMinimum(0);
   Graph_Graph1->SetMaximum(8.2);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleOffset(0.95);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleOffset(1.15);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph1);
   
   grae->Draw("ep");
   
   TLegend *leg = new TLegend(0.55,0.65,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(10);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dummy","Combined #pm 1#sigma","LF");

   ci = TColor::GetColor("#33cc33");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("","Per category #pm 1#sigma","LP");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TLine","#mu=#mu_{SM}","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(7);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
      tex = new TLatex(0.214,0.93,"#bf{CMS} #scale[0.75]{#it{Preliminary}}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.254,0.85,"H#rightarrow#gamma#gamma");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.665,0.93,"2.7fb^{-1} (13#scale[0.5]{ }TeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH2F *dummy__9 = new TH2F("dummy__9","",1,-2.5,9,8,0,8);
   dummy__9->SetDirectory(0);
   dummy__9->SetStats(0);

   ci = TColor::GetColor("#33cc33");
   dummy__9->SetFillColor(ci);
   dummy__9->GetXaxis()->SetTitle("#mu");
   dummy__9->GetXaxis()->SetLabelFont(42);
   dummy__9->GetXaxis()->SetLabelOffset(0.007);
   dummy__9->GetXaxis()->SetTitleSize(0.05);
   dummy__9->GetXaxis()->SetTitleOffset(0.95);
   dummy__9->GetXaxis()->SetTitleFont(42);
   dummy__9->GetYaxis()->SetBinLabel(1,"TTH Tags");
   dummy__9->GetYaxis()->SetBinLabel(2,"VBF Tag 1");
   dummy__9->GetYaxis()->SetBinLabel(3,"VBF Tag 0");
   dummy__9->GetYaxis()->SetBinLabel(4,"Untagged 3");
   dummy__9->GetYaxis()->SetBinLabel(5,"Untagged 2");
   dummy__9->GetYaxis()->SetBinLabel(6,"Untagged 1");
   dummy__9->GetYaxis()->SetBinLabel(7,"Untagged 0");
   dummy__9->GetYaxis()->SetBinLabel(8,"");
   dummy__9->GetYaxis()->SetLabelFont(42);
   dummy__9->GetYaxis()->SetLabelOffset(0.007);
   dummy__9->GetYaxis()->SetTitleSize(0.05);
   dummy__9->GetYaxis()->SetTitleOffset(1.15);
   dummy__9->GetYaxis()->SetTitleFont(42);
   dummy__9->GetZaxis()->SetLabelFont(42);
   dummy__9->GetZaxis()->SetLabelOffset(0.007);
   dummy__9->GetZaxis()->SetTitleSize(0.05);
   dummy__9->GetZaxis()->SetTitleFont(42);
   dummy__9->Draw("sameaxis");
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->Modified();
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->cd();
   MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0->SetSelected(MultiPdfChannelCompatibility-perTag-mergeTTH_debug_Untagged_0);
}
