{
//=========Macro generated from canvas: MultiPdfChannelCompatibility-perTagType_debug_Untagged/c
//=========  (Fri Aug 19 16:45:16 2016) by ROOT version5.34/18
   TCanvas *MultiPdfChannelCompatibility-perTagType_debug_Untagged = new TCanvas("MultiPdfChannelCompatibility-perTagType_debug_Untagged", "c",1,1,600,576);
   gStyle->SetOptStat(0);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetHighLightColor(2);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->Range(-5.974187,-0.6082291,10.1434,4.422182);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetFillColor(0);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetBorderMode(0);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetBorderSize(2);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetTickx(1);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetTicky(1);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetLeftMargin(0.2155525);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetRightMargin(0.07094134);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetTopMargin(0.08392603);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetBottomMargin(0.1209104);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetFrameBorderMode(0);
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetFrameBorderMode(0);
   
   TH2F *dummy = new TH2F("dummy","",1,-2.5,9,4,0,4);
   dummy->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#33cc33");
   dummy->SetFillColor(ci);
   dummy->GetXaxis()->SetTitle("#mu");
   dummy->GetXaxis()->SetLabelFont(42);
   dummy->GetXaxis()->SetLabelOffset(0.007);
   dummy->GetXaxis()->SetTitleSize(0.05);
   dummy->GetXaxis()->SetTitleOffset(0.95);
   dummy->GetXaxis()->SetTitleFont(42);
   dummy->GetYaxis()->SetBinLabel(1,"TTH Tags");
   dummy->GetYaxis()->SetBinLabel(2,"VBF Tags");
   dummy->GetYaxis()->SetBinLabel(3,"Untagged");
   dummy->GetYaxis()->SetBinLabel(4,"");
   dummy->GetYaxis()->SetLabelFont(42);
   dummy->GetYaxis()->SetLabelOffset(0.007);
   dummy->GetYaxis()->SetTitleSize(0.05);
   dummy->GetYaxis()->SetTitleOffset(1.15);
   dummy->GetYaxis()->SetTitleFont(42);
   dummy->GetZaxis()->SetLabelFont(42);
   dummy->GetZaxis()->SetLabelOffset(0.007);
   dummy->GetZaxis()->SetTitleSize(0.05);
   dummy->GetZaxis()->SetTitleFont(42);
   dummy->Draw("");
   TBox *box = new TBox(0.2848791,0,1.194908,3.995);

   ci = TColor::GetColor("#33cc33");
   box->SetFillColor(ci);
   box->SetLineStyle(0);
   box->Draw();
   TLine *line = new TLine(0.713603,0,0.713603,4);
   line->SetLineWidth(2);
   line->Draw();
   line = new TLine(1,0,1,4);

   ci = TColor::GetColor("#ff0000");
   line->SetLineColor(ci);
   line->SetLineStyle(7);
   line->SetLineWidth(5);
   line->Draw();
   TLatex *   tex = new TLatex(0.57,0.59,"#hat{#mu} =   0.71 ^{#font[122]{+}0.48}_{#font[122]{-}0.43}");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.57,0.5,"m_{H} = 125.09 GeV");
tex->SetNDC();
   tex->SetTextAlign(12);
   tex->SetTextFont(42);
   tex->SetTextSize(0.035);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TGraphAsymmErrors *grae = new TGraphAsymmErrors(4);
   grae->SetName("");
   grae->SetTitle("");
   grae->SetFillColor(1);
   grae->SetLineWidth(2);
   grae->SetMarkerStyle(21);
   grae->SetMarkerSize(1.5);
   grae->SetPoint(0,3.952993,0.5);
   grae->SetPointError(0,3.694812,4.638847,0,0);
   grae->SetPoint(1,1.137243,1.5);
   grae->SetPointError(1,1.096201,1.182636,0,0);
   grae->SetPoint(2,0.597374,2.5);
   grae->SetPointError(2,0.5026898,0.476617,0,0);
   grae->SetPoint(3,-999,3.5);
   grae->SetPointError(3,0,0,0,0);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","",100,-1099.759,109.351);
   Graph_Graph1->SetMinimum(0.2);
   Graph_Graph1->SetMaximum(3.8);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleOffset(0.95);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleOffset(1.15);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.05);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   grae->SetHistogram(Graph_Graph1);
   
   grae->Draw("ep");
   
   TLegend *leg = new TLegend(0.55,0.65,0.9,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(10);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("dummy","Combined #pm 1#sigma","LF");

   ci = TColor::GetColor("#33cc33");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("","Per category #pm 1#sigma","LP");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1.5);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TLine","#mu=#mu_{SM}","L");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(7);
   entry->SetLineWidth(5);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
      tex = new TLatex(0.214,0.93,"#bf{CMS} #scale[0.75]{#it{Preliminary}}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.254,0.85,"H#rightarrow#gamma#gamma");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.665,0.93,"2.7fb^{-1} (13#scale[0.5]{ }TeV)");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.045);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TH2F *dummy__5 = new TH2F("dummy__5","",1,-2.5,9,4,0,4);
   dummy__5->SetDirectory(0);
   dummy__5->SetStats(0);

   ci = TColor::GetColor("#33cc33");
   dummy__5->SetFillColor(ci);
   dummy__5->GetXaxis()->SetTitle("#mu");
   dummy__5->GetXaxis()->SetLabelFont(42);
   dummy__5->GetXaxis()->SetLabelOffset(0.007);
   dummy__5->GetXaxis()->SetTitleSize(0.05);
   dummy__5->GetXaxis()->SetTitleOffset(0.95);
   dummy__5->GetXaxis()->SetTitleFont(42);
   dummy__5->GetYaxis()->SetBinLabel(1,"TTH Tags");
   dummy__5->GetYaxis()->SetBinLabel(2,"VBF Tags");
   dummy__5->GetYaxis()->SetBinLabel(3,"Untagged");
   dummy__5->GetYaxis()->SetBinLabel(4,"");
   dummy__5->GetYaxis()->SetLabelFont(42);
   dummy__5->GetYaxis()->SetLabelOffset(0.007);
   dummy__5->GetYaxis()->SetTitleSize(0.05);
   dummy__5->GetYaxis()->SetTitleOffset(1.15);
   dummy__5->GetYaxis()->SetTitleFont(42);
   dummy__5->GetZaxis()->SetLabelFont(42);
   dummy__5->GetZaxis()->SetLabelOffset(0.007);
   dummy__5->GetZaxis()->SetTitleSize(0.05);
   dummy__5->GetZaxis()->SetTitleFont(42);
   dummy__5->Draw("sameaxis");
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->Modified();
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->cd();
   MultiPdfChannelCompatibility-perTagType_debug_Untagged->SetSelected(MultiPdfChannelCompatibility-perTagType_debug_Untagged);
}
